try {
  raise RuntimeError("example");
  assert(false);
} catch _ {
  assert(true);
}