try {
  raise Error("raise");
  assert(false);
} catch {

}