// self is a regression test. There was a bug where the VM would try to close
// an upvalue even if the upvalue was never created because the codepath for
// the closure was not executed.

{
  let a = "a";
  if (false) {
    fn foo() { a; }
  }
}

// If we get here, we didn't segfault when a went out of scope.
assert(true); // expect: ok
